### ISSUE TITLE
Quark engine does not report the same risk based on threshold

### ISSUE THREAD

**Issue by cryptax** [quark-engine/quark-engine#118]
I am using [this malicious sample again](https://koodous.com/apks/a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3).

I run : `quark -a a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3.apk -r ./quark-rules -s` and get a **Moderate Risk**.

![quark-moderate-risk](https://user-images.githubusercontent.com/2493690/107364767-2d486280-6adc-11eb-8109-e1187178f45f.png)

Now, if I set threshold to 100%, I get a **High Risk** !! This does not make sense. The sample did not change, the risk level should be the same whatever threshold I use.

![quark-high-risk](https://user-images.githubusercontent.com/2493690/107364944-697bc300-6adc-11eb-8de9-d55ff7e1cc40.png)

If I try with various thresholds:
- not specified, 20%, 40% : Moderate Risk
- 60%, 80%, 100%: High Risk

Test conditions:
- Quark v21.02.1
- Linux

**Comment by krnick** [comment]
It seems that if a threshold is added when calculating the score, other rules that are not met will be ignored. Thank you @cryptax for reporting this issue.

**Comment by 18z** [comment]
@cryptax thanks for reporting this issue. 😄 

Actually, despite that we have designed the so called "malware scoring system".

The scoring system takes effect only when we have enough amounts of detection rules.
And the problem here is, we are still thinking about what amount of rules should be enough.

Now let's skip the problem above and assume that we have enough rules.
Then we have issues concerning adjusting the weighting scores of each rule. :-D

TBH, Quark is now 50% of its power and I believe it will be 100% when we make scoring system really works.
