### ISSUE TITLE
error while updating IntelOwl

### ISSUE THREAD

**Issue by mlodic** [quark-engine/quark-engine#152]
Hi guys, I was trying to update IntelOwl to the latest version (21.3.3) of Quark and rules.

However, I have found this 

```
Error message: [Errno 13] Permission denied: '/root/.quark-engine'
```

Previously, I had the version 21.1.2. I looked for that string in the project and I found out this change: https://github.com/quark-engine/quark-engine/blame/master/quark/config.py that was released some patches after that version.

Could you please help me to understand how I can solve this problem without removing support for other kind of use-cases in Quark?

Thank you in advance guys and keep the good work 👍🏻

**Comment by krnick** [comment]
Hello @mlodic,

Thank you for reporting this issue. Could you kindly provide us with the operating system you are using?

This problem occurs when we want to update the [latest rules](https://github.com/quark-engine/quark-rules) from the GitHub repository after running quark. It will delete the existing GitHub directory under the home directory, which might cause the `permission denied`.

I'm trying to solve this problem before since it may have different behavior while removing the Git directory using Python on each operating system.

I will release the patch version on PyPi as soon as possible, then you only need to update the version.

**Comment by mlodic** [comment]
The error appears on the container generated by this [image](https://github.com/intelowlproject/IntelOwl/blob/master/docker/Dockerfile) (Debian Buster should be). This container contains the quark-rules extracted in this way with a [script launched](https://github.com/intelowlproject/IntelOwl/blob/8657623280c577569d1b722feabd2030dd77b61a/api_app/script_analyzers/yara_repo_downloader.sh#L63.) at build time.
Then the error appears once IntelOwl executes Quark with this [code](https://github.com/intelowlproject/IntelOwl/blob/quark_update/api_app/script_analyzers/file_analyzers/quark_engine.py)

Please tell me if you need more information

**Comment by krnick** [comment]
Hi @mlodic,

I have updated the latest version to "v21.3.4", where I removed the usage of the home directory while logging.

Could you please help us test again to see whether this problem will show up again, thank you 😄 !

**Comment by mlodic** [comment]
It works! Thank you!
