### ISSUE TITLE
click dependency issue with IntelOwl

### ISSUE THREAD

**Issue by mlodic** [quark-engine/quark-engine#180]
Hi everyone!

Regarding this line: https://github.com/quark-engine/quark-engine/blob/v21.6.1/setup.py#L36,
Is it necessary that specific `click` version? I am asking this because this creates conflicts in integrating the latest version (21.6.1) in [IntelOwl](https://github.com/intelowlproject/IntelOwl) because there are other dependencies (like `celery`) that do support only old `click` version. Is it possible to soften that dependency to allow the installation of `click` version 7 too?

Thank you in advance and keep up the great work guys :P

**Comment by krnick** [comment]
Hello @mlodic !

Thanks for letting me know about this problem.

We need the click version greater than **8.0.1** to apply the new command-line feature we just released in Quark version 21.6.1 since it can't install the latest version(8.0.1) via `pip3 install quark-engine` if we don't specify it.

However, the integration of Quark API won't be affected by the click version. Therefore, you can choose the click version as needed.

In this case, should we remove the specified click version(8.0.1) on setup.py, or can you manually specify the click version to make your dependencies work?

Thank you!

**Comment by mlodic** [comment]
yep I'll do the second one (manually specify the click version to make the dependencies work), thank you for your time! have a good GSoC :)

**Comment by krnick** [comment]
No problem!
We really appreciate your kind help in everything 😄 
Hope you have a good time on GSoC too!
