### ISSUE TITLE
Backward Compatible API

### ISSUE THREAD

**Issue by ajinabraham** [quark-engine/quark-engine#222]
**Is your feature request related to a problem? Please describe.**

The latest release from pypi has a breaking API change.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1770

```
Traceback (most recent call last):
  File "/home/runner/work/Mobile-Security-Framework-MobSF/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 227, in static_analyzer
    quark_results = quark_analysis(
  File "/home/runner/work/Mobile-Security-Framework-MobSF/Mobile-Security-Framework-MobSF/mobsf/MalwareAnalyzer/views/quark.py", line 27, in quark_analysis
    from quark.Objects.quark import Quark
ModuleNotFoundError: No module named 'quark.Objects'
Error:  19/Jul/2021 18:23:08 - No module named 'quark.Objects'
Error:  19/Jul/2021 18:23:08 - Internal Server Error: /api/v1/scan
Error:  19/Jul/2021 18:23:08 - Performing Static Analysis: android.apk
```

**Describe the solution you'd like**

It's ideal if the APIs used by other tools for integrating with quark engine is consistent across release.

**Describe alternatives you've considered**

**Additional context**

**Comment by haeter525** [comment]
Hi @ajinabraham ,

Thank you for reporting this issue!
It appears to be caused by the adjustment on module names in v21.7.1.
I will work on it now. And I will keep you updated if there is anything new.

**Comment by superpoussin22** [comment]
@haeter525 is there some progress ?
thanks

**Comment by haeter525** [comment]
Hi, @superpoussin22 

Sorry for getting back late.
I found that the integration incorrectly uses the internal API (`quark.object`) instead of Quark's [public consistent one](https://quark-engine.readthedocs.io/en/latest/integration.html#directory-scanning) (`quark.report`). As a result, it crashes when Quark gets updated.

We need to submit a patch to the MobSF repo for fixing the integration. However, there is already one ([#1771](https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1771)) working on it.
If you agree, I thought I could help update this PR. Thank you.

**Comment by superpoussin22** [comment]
@haeter525  thanks.
I'm able to make it work :) thanks for the pointer 
happy christmas

**Comment by superpoussin22** [comment]
issue can be closed

**Comment by haeter525** [comment]
Thank you, @superpoussin22 .
I will close this lately :D
