### ISSUE TITLE
Add a process for handling invalid issues

### ISSUE THREAD

**Issue by pulorsok** [quark-engine/quark-engine#252]
We need to define a process to handle the issues we cannot reproduce, especially if the issue raiser has not responded for a long time.

**Comment by sharteeya** [comment]
I agree with you. I've found that there are two types of those invalid issues:
1. The issue has already been removed/updated from Quark-Engine.
2. The issue can not reproduce or confirmed if it exists. And we lost contact with the user who hosts the issue.

**Suggestions:**
- For type 1, I suggest close them by marking an invalid label and a brief reply.
- For type 2, I suggest marking them with a test-require label after two weeks. If the situation remains, close them with an invalid label after one month.

**Examples of two types:**

- #74 (Type 1): The rule in this issue is invalid now due to updates of Quark-Engine.
- #226 (Type 2): The reference issue in MobSF still has no reply, and we can not reproduce the error.
