### ISSUE TITLE
CWE-489 Script - ImportError: cannot import name 'getApplication' from 'quark.script' (/home/kali/.local/lib/python3.10/site-packages/quark/script/__init__.py) ERROR

### ISSUE THREAD

**Issue by iremclk** [quark-engine/quark-engine#470]
Hi, when i try run CWE 489 Quark script, i get the following error. I checked __init__.py, but i didn't see getApplication method.
**Traceback (most recent call last):
  File "/home/kali/Downloads/Quark-Engine/CWE-489/CWE-489.py", line 1, in <module>
    from quark.script import getApplication
ImportError: cannot import name 'getApplication' from 'quark.script' (/home/kali/.local/lib/python3.10/site-packages/quark/script/__init__.py)**

**Comment by zinwang** [comment]
Hi @iremclk,
The issue occurs because the Quark package provided by `apt` is outdated. And for now, unfortunately, we cannot upload a newer version due to a dependency issue (#263). But we are still working on it.

As an alternative way, I recommend reinstalling Quark via the following commands to get the latest version from PyPI.
```
 sudo apt remove quark-engine
 pip3 install -U quark-engine
```
Also, we think the issue causes #469 and #471.

Hope you found this helpful :)

**Comment by zinwang** [comment]
We are closing this issue because it has been inactive for months.
Please feel free to open a new issue if you have any further questions.
