### ISSUE TITLE
Is it possible to scan multiple samples? For example, scan all apks in a directory

### ISSUE THREAD

**Issue by onemoreflag** [quark-engine/quark-engine#92]
Is it possible to scan multiple samples? For example, scan all apks in a directory

**Comment by krnick** [comment]
I think this may be a good feature when you need to analyze a large number of APKs in the future. Would you like to work on this pull request 😄 ?

**Comment by lordlabuckdas** [comment]
Hello @krnick, if this issue is up for grabs, I'd like to work on it 😃.

**Comment by krnick** [comment]
> Hello @krnick, if this issue is up for grabs, I'd like to work on it 😃.

Hi @lordlabuckdas Yeah, this issue has not been resolved. That would be great if you would like to work on it. Please let me know if you have any questions.

Thank you for your kind help 😄

**Comment by Surendrajat** [comment]
@lordlabuckdas I'd like to discuss the CLI interface for this one.
For example: if you make `-a` accept a **dir** or `*.apk` then how will it work with `-o` JSON output? Will it consolidate all reports in one file or separate? If one then what will be structure and if separate what is the naming scheme?
This is because many tools such as https://github.com/APKLab/APKLab depend on current CLI interface.
Anyway, it's a cool addition, and thanks for your interest.

**Comment by krnick** [comment]
> @lordlabuckdas I'd like to discuss the CLI interface for this one.
> For example: if you make `-a` accept a **dir** or `*.apk` then how will it work with `-o` JSON output? Will it consolidate all reports in one file or separate? If one then what will be structure and if separate what is the naming scheme?
> This is because many tools such as https://github.com/APKLab/APKLab depend on current CLI interface.
> Anyway, it's a cool addition, and thanks for your interest.

Indeed, I prefer not to modifying the current CLI interface and its original options since many tools already using the quark CLI interface.

In fact, if you need to scan multiple APKs, I think writing a shell script is actually sufficient. Or it can be done through [python binding API](https://quark-engine.readthedocs.io/en/latest/integration.html#second-step-code-snippet-as-you-go).

Maybe writing some example code in the documentation is a good way to show how to use the quark Python API instead of changing the existing CLI interface to scan multiple samples.

**Comment by lordlabuckdas** [comment]
Agreed, adding sample code for scanning directories in the docs seems to be the best approach. @Surendrajat @krnick

Will adding an example of the relevant bash and python code [here](https://quark-engine.readthedocs.io/en/latest/integration.html#second-step-code-snippet-as-you-go) and putting up a note (that provides the link to the page with example code to the users if they wish to scan directories) [here](https://quark-engine.readthedocs.io/en/latest/install.html) after Usage be okay?

**Comment by krnick** [comment]
> Agreed, adding sample code for scanning directories in the docs seems to be the best approach. @Surendrajat @krnick
> 
> Will adding an example of the relevant bash and python code [here](https://quark-engine.readthedocs.io/en/latest/integration.html#second-step-code-snippet-as-you-go) and putting up a note (that provides the link to the page with example code to the users if they wish to scan directories) [here](https://quark-engine.readthedocs.io/en/latest/install.html) after Usage be okay?

Yeah, that would be great!
Thank you @lordlabuckdas !
